// Trait declaration
pub mod replay;

// Replay formats
pub mod mhr;
pub mod gdr;
pub mod omegabot;
pub mod omegabot_2;
pub mod url;
pub mod tasbot;
pub mod mhr_binary;
pub mod ybot;
pub mod zbot;
pub mod plain_text;
pub mod replaybot;
pub mod xbot;
pub mod rush;
pub mod echo;
pub mod kdbot;
pub mod xdbot;
pub mod fembot;